### ISSUE TITLE
Can't seem to make work the simplest query

### ISSUE THREAD

**Issue by rhymes** [traildb/trck#11]
I've tried the following basic query:

```
main ->
    receive
        campaign_id = "1234" -> yield $counter
        * -> repeat
```

```sh
$ ./bin/trck query.tr data.tdb
Compiling query.tr
Produced binary in matcher-traildb in 0.53 seconds with gcc[no openmp]
no openmp support, using single thread
Opening traildb data.tdb
Opening traildb took 0 seconds
done processing traildb data.tdb,31s wallclock, 0 states 297522 match calls 0 windows applied to 297522 cookies
Merging thread results took 0
finalizing states took 0
Generating JSON output
{
"$counter":0}
```

I'm quite sure that the filter works:

```sh
$ tdb dump --filter='campaign_id=1234' -i data.tdb | wc -l
     436
```

I'm using the following:

- OSX
- Python 2.7 with ply installed
- traildb installed from brew
- judy 1.0.5
- trck manually compiled 

What am I doing wrong?

**Comment by oavdeev** [comment]
Any chance you could share the traildb file (or a subset of it)?

**Comment by rhymes** [comment]
@oavdeev Not really but I can't tell you how it's composed.

```python
In [1]: from traildb import TrailDB

In [2]: tdb = TrailDB('data.tdb')

In [3]: tdb.num_events
Out[3]: 69261656L

In [4]: tdb.num_trails
Out[4]: 148540L

In [5]: tdb.fields
Out[5]:
['time',
 'id',
 'app_version',
 'event_type',
 'event_time',
 'client_time',
 'event_user',
 'parameters',
 'campaign_id',
 'event_name',
 'payload',
 'flyer_id',
 'inserted']
```

parameters and payload are json encoded strings

I've also tried on Ubuntu Zesty 17.04 in the meantime but with no luck

```sh
$ ./bin/trck  ~/data/query.tr ~/data/data.tdb
Compiling /home/ubuntu/data/query.tr
Produced binary in matcher-traildb in 0.61 seconds with gcc[openmp]
max threads 4
Opening traildb /home/ubuntu/data/data.tdb
Opening traildb took 0 seconds
Opening traildb took 0 seconds
Opening traildb took 0 seconds
Opening traildb took 0 seconds
done processing traildb /home/ubuntu/data/data.tdb,2s wallclock, 0 states 148540 match calls 0 windows applied to 148540 cookies
Merging thread results took 0
finalizing states took 0
Generating JSON output
{
"$counter":0}

**Comment by oavdeev** [comment]
This toy example works for me:

**test.csv**
```
uuid time campaign_id
00000000000000000000000000000001 1 4567
00000000000000000000000000000000 2 1234
00000000000000000000000000000000 3 4567
00000000000000000000000000000000 4 1234
```

`tdb make --csv-header -i test.csv -o test.tdb`

Then
```
$ trck 1.tr test.tdb
...
Generating JSON output
{
"$counter":2}
```

So there must be something special about this particular dataset.

Is `campaign_id` literally `1234` or is there any special characters in it?

You could also run `trck -c --gen-c query.tr` to see the C code produced from the `query.tr`, it should be pretty straightforward: get numeric ids for `campaign_id` and `1234` in `match_db_init`, then checking for it in `match_trail`, something like:
```c
if (r) r = r && (item_get_value_id(item, ids->key_campaign_id) == ids->value_campaign_id_1234);
```

Another thing that came to my mind is that we normally use it with unix timestamps (in seconds), and timestamps in traildb were originally 32-bit only. Therefore there may be some issues with 64-bit timestamps in `trck` -- can you share the approximate timestamp range for this traildb?

**Comment by oavdeev** [comment]
Btw I've just fixed one issue with the 64-bit timestamps (in master)

**Comment by rhymes** [comment]
Hi,

I've created the C file for two revisions (pre and post fix), unfortunately it still doesn't work.

These are the files: [query_c.zip](https://github.com/traildb/trck/files/1138704/query_c.zip)

it contains two files, one for each revision. The diff is the following:

```diff
--- query_70da858.c	2017-07-11 13:30:44.000000000 +0200
+++ query_e08ddf9.c	2017-07-11 13:28:54.000000000 +0200
@@ -38,12 +38,12 @@
 }
 void match_trail_init(state_t *state)
 {
-    state->window_expires = UINT64_MAX;
+    state->window_expires = 4000000000;
     state->ri = 0;
 }
 bool match_is_initial_state(state_t *state)
 {
-    if (state->window_expires != 0 && state->window_expires != UINT64_MAX) return false;
+    if (state->window_expires != 0 && state->window_expires != 4000000000) return false;
     if (state->ri != 0) return false;
     return true;
 }
@@ -98,7 +98,7 @@
         case -1: abort = 1; goto STOP;
     }
     RULE_START_r0:
-    state->window_expires = UINT64_MAX;
+    state->window_expires = 4000000000;
     RULE_CONT_r0:
     state->ri = 0;
     DBG_PRINTF("entering rule \"main\" at pos %d, timestamp %" PRIu64 ", end_of_trail %d\n", ctx_get_position(ctx), timestamp, ctx_end_of_trail(ctx));
```

The file were produced with the brew version of traildb in OSX

**Comment by oavdeev** [comment]
Hmm ok, how about the `campaign_id` -- are there any special characters in it? Or anything special (compared to my toy csv) about the format of the `uuid` or timestamps there?

Another weird thing I just noticed that your `trck` output says it processed  297522 cookies, while that python session says there are just 148540 trails in the traildb. Dumb question but can you please double check it is the same traildb file? There is one feature of libtraildb that is sometimes confusing to me personally, it automatically adds .tdb extension even if it is already there so sometimes I end up with `mydata.tdb` and `mydata.tdb.tdb`.
